<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NuvyntraLabs.NET.ApiLens.UI</RootNamespace>
    <Description>Embedded development dashboard page for NuvyntraLabs.NET.ApiLens.</Description>
    <PackageTags>diagnostics;apilens;nuvyntra</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="dashboard.html" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
